export const moviesTitle = [
  'Toy Story',
  'The Godfather',
  'Jerry Maguire',
  'The Tourist',
  'Jumanji',
  'The Matrix',
  'What Women Want',
  'The Adjustment Bureau',
  'A Clockwork Orange',
  'Pretty Woman',
  'Mrs Doubtfire',
  'Pulp Fiction',
  'Saw',
  'Finding Nemo',
  'Frozen',
  'It',
  'Bean',
  'The Dictator',
  'The Hunger Games',
  'The Da Vinci Code',
  'The Bourne Ultimatum',
  'Home Alone',
  'Love Actually',
  'Scream',
  'Black Swan',
  'Captain Marvel',
  'The Nun',
  'Shrek',
  'The kissing booth 2',
  'Desperados',
  'My Spy',
  'Uncorked',
  'Fatal Affair',
  '365 Days'
]